# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
ADD config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# Example: RUN elasticsearch-plugin install analysis-icu
