version: "3.4"

services:

  gateway:
    image: devsu/grpc-gateway
    volumes:
      - ./gateway/config.json:/opt/generator/config/config.json
      - ./protos/:/opt/generator/protos/
    ports:
      - 9090
    networks:
      - banknet

  bank:
    build:
      context: .
      dockerfile: bank.Dockerfile
    image: acqio/bank
    networks:
      - banknet
    ports:
      - 3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.7
    environment:
      MONGO_INITDB_ROOT_USERNAME: bank
      MONGO_INITDB_ROOT_PASSWORD: bank
    volumes:
      - mongodb-vol:/data/db
    networks:
      - banknet

  mongodb-admin:
    image: mongo-express:0.45
    ports:
      - 8081
    environment:
      ME_CONFIG_SITE_BASEURL: /mongoadmin/
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: bank
      ME_CONFIG_MONGODB_ADMINPASSWORD: bank
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - banknet
  nginx:
    build:
      context: nginx/
    image: acqio/nginx
    ports:
      - "80:80"
    networks:
      - banknet
    depends_on:
      - mongodb-admin
      - gateway

  logspout:
    build:
      context: logspout/
    image: acqio/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash://logstash:5000
      LOGSTASH_TAGS: elk
      LOGSPOUT: ignore
    networks:
      - elknet

networks:
  banknet:
  elknet:
    external:
      name: elk_elknet

volumes:
  mongodb-vol:
