version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    image: acqio/elasticsearch
    ports:
      - "9200/tcp"
      - "9300/tcp"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elknet
    volumes:
      - elk-vol:/var/lib/elasticsearch
    environment:
      LOGSPOUT: ignore

  logstash:
    build:
      context: logstash/
    image: acqio/logstash
    ports:
      - "5000/tcp"
      - "5001/tcp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elknet
    depends_on:
      - elasticsearch
    environment:
      LOGSPOUT: ignore


  kibana:
    build:
      context: kibana/
    image: acqio/kibana
    ports:
      - "5601:5601"
    networks:
      - elknet
    depends_on:
      - elasticsearch
    environment:
      LOGSPOUT: ignore

networks:
  elknet:
    driver: bridge

volumes:
  elk-vol:
